"""RES Phase 4 tests: bias/scale fits recover known corrections; calibrated CFs hit the bands."""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
from res_model.calibration.fit import _fit_pv_bias, _fit_wind
from res_model.calibration.model import CalibratedRes
from res_model.config import load_config
from res_model.conversion.wind_onshore import onshore_cf


def test_pv_bias_recovers_correction():
    idx = pd.date_range("2020-01-01", periods=24 * 365 * 2, freq="h", tz="UTC")
    # modelled has a known monthly-hour bias vs "observed"
    base = np.clip(np.sin((idx.hour - 6) / 12 * np.pi), 0, None) * (0.4 + 0.4 * np.sin(idx.dayofyear / 365 * np.pi))
    mod = pd.Series(base, index=idx)
    obs = mod * 1.2                                          # observed = 1.2× modelled everywhere
    train = np.ones(len(idx), bool)
    bias = _fit_pv_bias(mod, obs, train)
    daylit = [v for (m, h), v in bias.items() if 8 <= h <= 16]
    assert 1.1 < np.mean(daylit) < 1.3                       # recovers the ~1.2 factor

    cal = CalibratedRes(pv_bias=bias, onshore={}, offshore={}, hydro={})
    corrected = cal.apply_pv(mod)
    assert abs(corrected.sum() - obs.sum()) / obs.sum() < 0.05


def test_wind_fit_matches_distribution():
    idx = pd.date_range("2019-01-01", periods=24 * 365 * 3, freq="h", tz="UTC")
    rng = np.random.default_rng(0)
    w100 = pd.Series(np.abs(rng.weibull(2.0, len(idx)) * 9.0), index=idx)
    # "observed" CF generated by a known curve (sp=280, sm=2.5) × 0.9
    obs = onshore_cf(w100, specific_power=280, smoothing_ms=2.5, availability=1.0) * 0.9
    train = np.ones(len(idx), bool)
    params, _ = _fit_wind(w100, obs, train, (250, 280, 300, 330, 360), (1.0, 2.0, 2.5, 3.0))
    cf = (onshore_cf(w100, specific_power=params["specific_power"], smoothing_ms=params["smoothing_ms"],
                     availability=1.0) * params["cf_scale"]).clip(0, 1)
    assert abs(cf.mean() - obs.mean()) / obs.mean() < 0.05   # mean matched
    assert abs(np.quantile(cf, 0.9) - np.quantile(obs, 0.9)) < 0.05   # upper distribution matched


def test_hydro_blend_recovers_soil_signal():
    from res_model.calibration.hydro import FEATURES, apply_blend, feature_frame, fit_blend
    idx = pd.date_range("2016-01-01", periods=24 * 365 * 6, freq="h", tz="UTC")
    rng = np.random.default_rng(0)
    precip = pd.Series(np.clip(rng.gamma(0.3, 3.0, len(idx)), 0, None), index=idx)
    temp = pd.Series(12 - 9 * np.cos(2 * np.pi * idx.dayofyear / 365) + rng.normal(0, 2, len(idx)), index=idx)
    pd_daily = precip.resample("1D").sum(); td_daily = temp.resample("1D").mean()
    # synthetic ROR: seasonal climatology + genuine dependence on the slow soil-moisture store
    F = feature_frame(pd_daily, td_daily)
    sm = (F["SM_slow"] - F["SM_slow"].mean()) / F["SM_slow"].std()
    doy = pd_daily.index.dayofyear
    ror_daily = (0.40 - 0.12 * np.cos(2 * np.pi * doy / 365) + 0.06 * sm.fillna(0)).clip(0.05, 0.8)
    ror = ror_daily.reindex(idx.normalize()).clip(0.05, 0.8); ror.index = idx
    params = fit_blend(pd_daily, td_daily, ror, holdout_years={2021})
    assert set(params["beta"]) == set(FEATURES)
    cf = apply_blend(params, pd_daily, td_daily)
    # blend beats a pure-climatology model on the held-out year
    hy = cf.index.year == 2021
    clim = pd.Series([params["monthly_clim"][m] for m in cf.index.month], index=cf.index)
    o = ror_daily.reindex(cf.index)
    err_blend = float(np.nanmean(np.abs(cf[hy] - o[hy])))
    err_clim = float(np.nanmean(np.abs(clim[hy] - o[hy])))
    assert err_blend < err_clim                      # the weather blend adds real skill


def test_calibrated_bands_real():
    cfg = load_config("config.yaml")
    p = cfg.models_dir / "calibrated_res.json"
    if not p.exists():
        pytest.skip("calibrated_res.json not built yet")
    m = CalibratedRes.load(p).metrics
    b = cfg.section("validation")["cf_bands"]
    assert b["pv"]["low"] - 0.02 <= m["mean_cf"]["pv"] <= b["pv"]["high"] + 0.02
    assert b["wind_onshore"]["low"] - 0.03 <= m["mean_cf"]["wind_onshore"] <= b["wind_onshore"]["high"] + 0.03
    assert 3.0 <= m["pv_jul_dec_ratio"] <= 6.0
    # holdout monthly energy bias within a few % for the weather-driven techs
    assert m["monthly_energy_bias_pct"]["pv"] < 8.0
